print("¿Que operacion quieres realizar?")
print("1 para multiplicar")
print("2 para dividir")
print("3 para sumar")
print("4 para restar")
print("5 para modulo")
opcion=int(input("elije la opcion:"))
if(opcion==1):
    print("elegiste multiplicar:")
    a=input("inserta el número:")
    b=input("inserta el segundo numero que vas multiplicar:")
    resultado=int(a)*int(b)
    print("el resultado de la multiplicacion es:",resultado)
if(opcion==2):
    print("elegiste dividir:")
    a=input("inserta el número:")
    b=input("inserta el segundo numero que vas dividir:")
    resultado=int(a)/int(b)
    print("el resultado de la división es:",resultado)
if(opcion==3):
    print("elegiste sumar:")
    a=input("inserta el número:")
    b=input("inserta el segundo numero que vas sumar:")
    resultado=int(a)+int(b)
    print("el resultado de la suma es:",resultado)
if(opcion==4):
    print("elegiste resta:")
    a=input("inserta el número:")
    b=input("inserta el segundo numero que vas restar:")
    resultado=int(a)-int(b)
    print("el resultado de la resta es:",resultado)
if(opcion==5):
    print("elegiste modulo:")
    a=input("inserta el número:")
    b=input("inserta el segundo numero que vas modular:")
    resultado=int(a)%int(b)
    print("el resultado del modulo es:",resultado)
